ALTER TABLE siswa 
ADD COLUMN nilai_sem1 DECIMAL(5,2) DEFAULT 0,
ADD COLUMN nilai_sem2 DECIMAL(5,2) DEFAULT 0,
ADD COLUMN nilai_sem3 DECIMAL(5,2) DEFAULT 0,
ADD COLUMN nilai_sem4 DECIMAL(5,2) DEFAULT 0,
ADD COLUMN nilai_sem5 DECIMAL(5,2) DEFAULT 0,
ADD COLUMN file_rapor VARCHAR(255) NULL,
ADD COLUMN file_kk_lama VARCHAR(255) NULL;
